PROJECT_ROOT ?= $(abspath ../../..)
include $(PROJECT_ROOT)/build/def.mk

CONFIG_FILES += abc.conf ddd.conf
ADDED_FILES += this_is_a_test this_is_a_test2 aa

SOURCE_DIRS = .

include $(PROJECT_ROOT)/build/bin.mk
