PROJECT_ROOT ?= $(abspath ../../..)
include $(PROJECT_ROOT)/build/def.mk

MODULE_NAME = speed_test_srv
SOURCE_DIRS = .
INCLUDE_DIRS += ../include
LOADLIBES += -lpthread
include $(PROJECT_ROOT)/build/bin.mk
