include ../build/def.mk

SUBDIRS += futex http inotify json libcurl libev libevent libparted
SUBDIRS += libudev mem multicast regex shm socket speed_test sqlite xml
# SUBDIRS += aio
# SUBDIRS += libnice netlink socket zmq
include ../build/subdir.mk
